name: Animacion de Gael

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *" # Se ejecuta cada hora automáticamente
  workflow_dispatch:      # Permite darle al botón "Run" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar gifos
        run: pip install gifos

      - name: Ejecutar script de Gael
        run: python gael_animacion.py

      - name: Guardar y subir GIF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GaelBot"
          git add output.gif
          git commit -m "Actualizando animacion" || exit 0
          git push
